### ISSUE TITLE
获取信息时出现报错

### ISSUE THREAD

**Issue by FurLC** [LiLuo-B/nonebot-plugin-mcsm#7]
错误日志：

> 08-18 12:28:37 [ERROR] nonebot | Running AlconnaMatcher(type='message', module=nonebot_plugin_mcsm.__main__, lineno=23) failed.
Traceback (most recent call last):
  File "<string>", line 15, in <module>
  File "/root/lengchuan-bot/.venv/lib/python3.12/site-packages/nonebot/__init__.py", line 335, in run
    get_driver().run(*args, **kwargs)
  File "/root/lengchuan-bot/.venv/lib/python3.12/site-packages/nonebot/drivers/fastapi.py", line 186, in run
    uvicorn.run(
  File "/root/lengchuan-bot/.venv/lib/python3.12/site-packages/uvicorn/main.py", line 577, in run
    server.run()
  File "/root/lengchuan-bot/.venv/lib/python3.12/site-packages/uvicorn/server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
  File "/usr/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "/root/lengchuan-bot/.venv/lib/python3.12/site-packages/nonebot/message.py", line 476, in check_and_run_matcher
    await _run_matcher(
> File "/root/lengchuan-bot/.venv/lib/python3.12/site-packages/nonebot/message.py", line 428, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/root/lengchuan-bot/.venv/lib/python3.12/site-packages/nonebot/internal/matcher/matcher.py", line 850, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/root/lengchuan-bot/.venv/lib/python3.12/site-packages/nonebot/internal/matcher/matcher.py", line 825, in simple_run
    await handler(
  File "/root/lengchuan-bot/.venv/lib/python3.12/site-packages/nonebot/dependencies/__init__.py", line 94, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "/root/lengchuan-bot/.venv/lib/python3.12/site-packages/nonebot_plugin_mcsm/__main__.py", line 88, in _
    nodes = await get_node_list()
  File "/root/lengchuan-bot/.venv/lib/python3.12/site-packages/nonebot_plugin_mcsm/mcsm_api.py", line 29, in get_node_list
    data = response.json()
  File "/root/lengchuan-bot/.venv/lib/python3.12/site-packages/httpx/_models.py", line 764, in json
    return jsonlib.loads(self.content, **kwargs)
  File "/usr/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by LiLuo-B** [comment]
你这报错我这边复现不了，mcsm_api.py 29行后面加个print(data)看看

**Comment by FurLC** [comment]
降级为python10之后没有出现，具体原因有可能是apikey填写错误，谢谢
